# Generated by Django 3.2.11 on 2022-01-21 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainPage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.CharField(max_length=500)),
                ('writer', models.CharField(max_length=200)),
                ('registered_date', models.DateTimeField()),
                ('comment', models.CharField(max_length=200)),
                ('like', models.IntegerField()),
                ('img', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid', models.IntegerField()),
                ('content', models.CharField(max_length=200)),
                ('writer', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Interior_obj',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=20)),
                ('obj_name', models.CharField(max_length=50)),
                ('detail_link', models.CharField(max_length=200)),
                ('minimal', models.IntegerField()),
                ('modern', models.IntegerField()),
                ('vintage', models.IntegerField()),
                ('natural', models.IntegerField()),
                ('individuality', models.IntegerField()),
                ('romantic', models.IntegerField()),
                ('casual', models.IntegerField()),
                ('useful', models.IntegerField()),
                ('enfj', models.FloatField()),
                ('enfp', models.FloatField()),
                ('entj', models.FloatField()),
                ('entp', models.FloatField()),
                ('esfj', models.FloatField()),
                ('esfp', models.FloatField()),
                ('estj', models.FloatField()),
                ('estp', models.FloatField()),
                ('infj', models.FloatField()),
                ('infp', models.FloatField()),
                ('intj', models.FloatField()),
                ('intp', models.FloatField()),
                ('isfj', models.FloatField()),
                ('isfp', models.FloatField()),
                ('istj', models.FloatField()),
                ('istp', models.FloatField()),
                ('like', models.IntegerField()),
                ('photo_link', models.CharField(max_length=200)),
            ],
        ),
    ]
