# Generated by Django 3.2.11 on 2022-01-25 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainPage', '0002_board_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='registered_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
