# Generated by Django 3.2.11 on 2022-01-25 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainPage', '0005_alter_board_like'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.RemoveField(
            model_name='board',
            name='comment',
        ),
    ]
